[package]
name = "trailborn"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-std = "1.13.1"
fixed = "1.29.0"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
rand = "0.9.1"
