[package]
name = "trailborn"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
fixed = "1.29.0"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
papaya = "0.2.1"
